import type { AppProps } from 'next/app'
import Head from 'next/head'
import React from 'react'
import '../src/main.css'


function MyApp({ Component, pageProps }: AppProps) {
  return <>
        <Head>
        <title>Arseny - choose your tags!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" />
      </Head>
      <Component {...pageProps} />
  </>
}
export default MyApp
